// Checksummed string encoding for the 32-byte identity seed.
//
// The display/generation form is classic BIP-173 bech32 (no length limit — the
// same primitive the age-style recipient codec uses) under the HRP
// `l309-seed-`, returned UPPERCASE: `L309-SEED-1…`. Secrets are loud: the
// uppercase form is visually unmistakable next to lowercase recipient
// addresses (`age1…`, `age1pqc…`), mirroring age's `AGE-SECRET-KEY-1…`
// convention, and the checksum deterministically catches typos and truncation.
//
// Parsing accepts two representations:
//   • the bech32 form in all-lowercase or all-uppercase (mixed case is
//     rejected per BIP-173), checksum verified, HRP exactly `l309-seed-`,
//     payload exactly 32 bytes;
//   • raw hex — 64 hex digits, case-insensitive, tolerating a `0x` prefix and
//     surrounding/internal whitespace — the lowest-common-denominator
//     interchange form, so a seed generated by any external tool imports.

import { bech32DecodeNoLimit, bech32EncodeNoLimit } from '../recipient/bech32';
import { hexToBytes } from '../util/hex';

import { SeedEncodingError } from './errors';

// The bech32 human-readable part. The trailing hyphen is part of the HRP, so
// with the bech32 separator `1` the rendered prefix reads `l309-seed-1…`.
export const IDENTITY_SEED_HRP = 'l309-seed-';

const SEED_LENGTH = 32;
const SEED_HEX_DIGITS = 64;

// ASCII-case-insensitive probe: does the input claim to be the bech32 form?
// Decides whether a decode failure is reported as a corrupted seed string
// (`SEED_STRING_BAD_CHECKSUM`) or as unrecognized input. A non-`u` RegExp `i`
// flag never case-matches a non-ASCII character to an ASCII one, so the probe
// cannot be spoofed by Unicode case folding.
const CLAIMS_SEED_PREFIX = /^l309-seed-1/i;

// Encode a 32-byte identity seed to its checksummed display form
// (`L309-SEED-1…`, ~69 characters).
//
// Throws `SeedEncodingError` (`INVALID_SEED_LENGTH`) unless the seed is
// exactly 32 bytes.
export function encodeIdentitySeed(seed: Uint8Array): string {
  if (seed.length !== SEED_LENGTH) {
    throw new SeedEncodingError(
      'INVALID_SEED_LENGTH',
      `seed must be exactly 32 bytes, got ${seed.length}`,
    );
  }
  return bech32EncodeNoLimit(IDENTITY_SEED_HRP, seed).toUpperCase();
}

// Parse an identity seed from either accepted representation (the checksummed
// bech32 form in a single case, or 64-digit raw hex) back to its 32 raw bytes.
// The inverse of `encodeIdentitySeed` for the bech32 form.
//
// Throws `SeedEncodingError` with the code naming what was wrong: a mixed-case
// bech32 string, a failed checksum, a foreign HRP (e.g. an age recipient
// pasted by mistake), a wrong payload or hex-digit length, or input that is
// neither representation.
export function parseIdentitySeed(input: string): Uint8Array {
  // Hex path: strip ALL whitespace and an optional 0x prefix; if what remains
  // is pure hex it can only be meant as a hex seed (the bech32 form always
  // carries non-hex characters: the HRP's `l`, `s`, and `-`).
  const compact = input.replace(/\s+/g, '');
  const hexBody = compact.startsWith('0x') || compact.startsWith('0X') ? compact.slice(2) : compact;
  if (hexBody.length > 0 && /^[0-9a-fA-F]+$/.test(hexBody)) {
    if (hexBody.length !== SEED_HEX_DIGITS) {
      throw new SeedEncodingError(
        'SEED_STRING_WRONG_LENGTH',
        `hex seed must be exactly 64 hex digits, got ${hexBody.length}`,
      );
    }
    return hexToBytes(hexBody.toLowerCase());
  }

  // Bech32 path: a single token, so only surrounding whitespace is tolerated.
  const candidate = input.trim();
  const claimed = CLAIMS_SEED_PREFIX.test(candidate);
  if (claimed && /[a-z]/.test(candidate) && /[A-Z]/.test(candidate)) {
    throw new SeedEncodingError(
      'SEED_STRING_MIXED_CASE',
      'identity-seed string mixes upper and lower case; use one case only',
    );
  }
  let decoded: { hrp: string; bytes: Uint8Array };
  try {
    decoded = bech32DecodeNoLimit(candidate);
  } catch (cause) {
    if (claimed) {
      throw new SeedEncodingError(
        'SEED_STRING_BAD_CHECKSUM',
        'identity-seed string failed bech32 decoding (checksum, character set, or structure)',
        { cause },
      );
    }
    throw new SeedEncodingError(
      'SEED_STRING_UNRECOGNIZED',
      'expected a 64-hex-digit seed or an L309-SEED-1… string',
      { cause },
    );
  }
  if (decoded.hrp !== IDENTITY_SEED_HRP) {
    throw new SeedEncodingError(
      'SEED_STRING_WRONG_HRP',
      `expected the bech32 prefix "${IDENTITY_SEED_HRP}", got "${decoded.hrp}"`,
    );
  }
  if (decoded.bytes.length !== SEED_LENGTH) {
    throw new SeedEncodingError(
      'SEED_STRING_WRONG_LENGTH',
      `identity-seed payload must be exactly 32 bytes, got ${decoded.bytes.length}`,
    );
  }
  return decoded.bytes;
}
